- name: Install MySQL and Dependencies
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Install User my.cnf to /root/.my.cnf
  template: src=usermy.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0640

- name: Reset MySQL root password
  mysql_user: name=root password={{ mysql_root_password }} state=present check_implicit_admin=true

- name: Create MySQL Database
  mysql_db: name=wordpress state=present

- name: Create MySQL User with correct db permissions
  mysql_user: name={{ mysql_db_username }} password={{ mysql_db_userpass }} priv=wordpress.*:ALL,GRANT state=present
