- name: Install default packages
  apt: name={{ item }} state=installed
  with_items:
    - tcptraceroute
    - nmap
    - iftop
    - iotop
    - htop
    - screen
    - unzip
    - unrar
    - tree
    - tcpdump
    - mlocate
    - nano
  register: install_pkg1
