- name: Install PostgreSQL
  apt: name={{ item }} state=latest
  with_items:
    - postgresql-9.5
    - python-psycopg2

- name: installing postgresql.conf template
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.5/main/postgresql.conf
  register: pgsql_template_postgresqlconf

- name: Installing pg_hba.conf template
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf
  register: pgsql_template_pghba

- name: Restart PostgreSQL upon config file change
  service: name=postgresql state=restarted
  when: (pgsql_template_postgresqlconf.changed) or (pgsql_template_pghba.changed)

- name: Creating PostgreSQL database for Drupal
  postgresql_db: name={{ pgsql_db_name }} encoding='UTF-8' lc_collate='en_GB.UTF-8' lc_ctype='en_GB.UTF-8' template='template0'

- name: Creating PostgreSQL user for Drupal
  postgresql_user: db={{ pgsql_db_name }} name={{ pgsql_db_username }} password={{ pgsql_db_userpass }} priv=ALL
