- name: Create certbot install dir
  file: dest={{ certbot_installdir }} state=directory owner=root group=root mode=0750
  tags: certbot

- name: Download Letsencrypt Certbot
  get_url: url={{ certbot_url }} dest={{ certbot_installdir }} owner=root group=root mode=0750
  tags: certbot

- name: Install or Update certbot using certbot-auto script
  command: "{{ certbot_installdir }}/certbot-auto --noninteractive --os-packages-only"
  ignore_errors: True
  tags: certbot

- name: Initialize certbot environment
  command: "{{ certbot_installdir }}/certbot-auto --noninteractive"
  args:
    creates: /root/.local/share/letsencrypt/bin/certbot
  ignore_errors: True
  tags: certbot

- name: Creating webroot folder structure for certbot
  file: dest="{{ vhostspath }}/{{ vhostfqdn }}/.well-known/acme-challenge" state=directory owner=root group={{ nginx_user }} mode=0750 recurse=yes
  tags: certbot

- name: Creating configs directory for letsencrypt
  file: dest=/etc/letsencrypt/configs state=directory owner=root group=root mode=0750
  tags: certbot

- name: Creating certbot configuration file from template
  template: src=certbot.conf.j2 dest=/etc/letsencrypt/configs/{{ vhostfqdn }}.conf
  tags: certbot
  
