- name: Install Spacewalk repository RPM
  yum: name=http://yum.spacewalkproject.org/2.4/RHEL/6/x86_64/spacewalk-repo-2.4-3.el6.noarch.rpm state=installed
  register: spacewalk_install_spacewalkrepo
  when: common_install_epelrepo|success

- name: Install JPackage repository template
  template: src=jpackage-generic.repo.j2 dest=/etc/yum.repos.d/jpackage-generic.repo
  register: spacewalk_install_jpackagerepo

- name: Install Spacewalk PostgreSQL
  yum: name=spacewalk-setup-postgresql state=installed
  register: spacewalk_install_spacewalkpostgresql
  when: spacewalk_install_jpackagerepo|success

- name: Install Spacewalk
  yum: name=spacewalk-postgresql state=installed
  register: spacewalk_install_spacewalk
  when: spacewalk_install_spacewalkpostgresql|success
