---
- hosts: 192.168.111.119
  gather_facts: yes
  vars:
    - pgsql_db_name: drupal
    - pgsql_db_username: drupaluser
    - pgsql_db_userpass: MyDBPassw0rd
    - pgsql_db_host: 127.0.0.1
    - pgsql_pghba_host: "{{ pgsql_db_host }}/32"
    - pgsql_db_authmode: md5

    - vhostfqdn: sego.hu
    - drupalversion: 7.43
    - drush_admin_username: admin
    - drush_admin_userpass: Passw0rd
    - drush_admin_email: gorkhaan@gmail.com

  tasks:

  #- name: download latest drush
  #  get_url: url=https://github.com/drush-ops/drush/releases/download/8.1.2/drush.phar dest=/opt/drush mode=0555

  - name: testing
    command: >
      /opt/drushlol/bin/drush --yes si standard
      --site-name={{ vhostfqdn }}
      --account-name={{ drush_admin_username }}
      --account-pass={{ drush_admin_userpass }}
      --db-url=pgsql://{{ pgsql_db_username }}:{{ pgsql_db_userpass }}@{{ pgsql_db_host}}:/{{ pgsql_db_name }}
    args:
      chdir: /opt/www/{{ vhostfqdn }}
    register: lol

  - debug: var=lol



#      drush si standard -y
#      --site-name={{ vhostfqdn }}
#      --account-name={{ drush_admin_username }}
#      --account-pass={{ drush_admin_userpass }}
#      --db-url=pgsql://{{ pgsql_db_username }}:{{ pgsql_db_userpass }}@{{ pgsql_db_host}}:/{{ pgsql_db_name }}
