- name: Install nginx
  apt: name=nginx-extras state=latest
  tags: nginx

- name: Remove default virtualhost
  file: dest=/etc/nginx/sites-enabled/default state=absent
  tags: nginx

- name: Install nginx main config from template
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
  register: nginx_template_nginxconf
  tags: nginx

- name: Ensure ansible virtualhost directory exists to load virtualhosts from
  file: dest=/etc/nginx/conf.d/ansible state=directory owner=root group=root mode=755
  tags: nginx

- name: Install nginx wordpress virtualhost config from template
  template: src=wpvhost.conf.j2 dest=/etc/nginx/conf.d/ansible/{{ vhostfqdn }}.conf owner=www-data group=www-data mode=0644
  register: nginx_template_wpvhost_http
  tags: nginx

- name: Restart nginx
  service: name=nginx state=restarted
  when: nginx_template_wpvhost_http.changed
  tags: nginx

- name: Request a certificate from letsencrypt using certbot
  command: "certbot-auto --agree-tos --config /etc/letsencrypt/configs/{{ vhostfqdn }}.conf certonly"
  args:
    creates: /etc/letsencrypt/live/gabit.hu/cert.pem
  tags: nginx

- name: Install nginx wordpress virtualhost config from template
  template: src=wpvhost-ssl.conf.j2 dest=/etc/nginx/conf.d/ansible/{{ vhostfqdn }}.conf owner=www-data group=www-data mode=0644
  register: nginx_template_wpvhost_https
  tags: nginx

- name: Install fastcgi microcache configuration
  template: src=microcache.conf.j2 dest=/etc/nginx/conf.d/ansible/microcache.conf owner=www-data group=www-data mode=0644
  tags: nginx

- name: Creating folder for virtualhosts data
  file: path=/opt/www/{{ vhostfqdn }} state=directory owner=root group=root mode=755
  tags: nginx

- name: Restart nginx
  service: name=nginx state=restarted
  when: (nginx_template_wpvhost_https.changed) or (nginx_template_nginxconf.changed)
  tags: nginx

- name: Install cronjob for certificate renewal
  cron: name="Certbot cert renewal" minute="0" hour="3" weekday="0" job="{{ certbot_installdir }}/certbot-auto renew &> /dev/null"
  tags: nginx
