- name: Installing Drupal CLI called drush
  apt: name=drush state=latest

- name: Creating temp download folder
  file: path=/opt/drupalsrc state=directory

- name: Downloading Drupal source
  # Ansible 2.1 version needed for this===> unarchive: src=https://ftp.drupal.org/files/projects/drupal-{{ drupalversion }}.tar.gz dest=/opt/www/{{ vhostfqdn }} copy=no creates=/opt/www/{{ vhostfqdn }}/index.php extra_opts="--strip-component 1"
  #unarchive: src=https://ftp.drupal.org/files/projects/drupal-{{ drupalversion }}.tar.gz dest=/opt/drupalsrc/ copy=no creates=/opt/drupalsrc/drupal-{{ drupalversion }}
  get_url: url=https://ftp.drupal.org/files/projects/drupal-{{ drupalversion }}.tar.gz dest=/opt/drupalsrc/drupal-{{ drupalversion }}.tar.gz
  register: drupal_download_source

- stat: path=/opt/www/{{ vhostfqdn }}/index.php
  register: drupal_already_installed

- name: Installing Drupal to virtualhost folder
  #command: creates=/opt/www/{{ vhostfqdn }}/index.php "cp -ar /opt/drupalsrc/drupal-{{ drupalversion }} /opt/www/{{ vhostfqdn }}"
  command: "tar -xzf /opt/drupalsrc/drupal-{{ drupalversion }}.tar.gz -C /opt/www/{{ vhostfqdn }} --strip-component 1"
  when: (drupal_download_source|success) and (drupal_already_installed.stat.exists == False)

- name: Installing Hungarian language for drupal
  get_url: url=http://ftp.drupal.org/files/translations/7.x/drupal/drupal-{{ drupalversion }}.hu.po dest=/opt/www/{{ vhostfqdn }}/profiles/standard/translations/drupal-7.43.hu.po

#- name: Modify permissions on settings folder for drupal
#  file: path=/opt/www/{{ vhostfqdn}}/sites/default owner=www-data group=root mode=0750

#- name: Copy default.settings.php to settings.php
  #copy: src=/opt/www/{{ vhostfqdn }}/sites/default/default.settings.php dest=/opt/www/{{ vhostfqdn }}/sites/default/settings.php owner=www-data group=root mode=0640 remote_src=yes

- name: Setting up default drupal site with drush
  command: >
      /opt/drushlol/bin/drush site-install standard
      --site-name={{ vhostfqdn }}
      --site-mail={{ drush_site_email }}
      --account-name={{ drush_admin_username }}
      --account-pass={{ drush_admin_userpass }}
      --account-mail={{ drush_admin_email }}
      --locale={{ drush_site_locale }}
      --db-url=pgsql://{{ pgsql_db_username }}:{{ pgsql_db_userpass }}@{{ pgsql_db_host }}:/{{ pgsql_db_name }}
      -y
  args:
    chdir: "/opt/www/{{ vhostfqdn }}"
#  tags:
#    - drush

#- name: Setting up default drupal site with drush
# - command: >
#       drush si standard -y
#       --site-name={{ vhostfqdn }}
#       --account-name={{ drush_admin_username }}
#       --account-pass={{ drush_admin_userpass }}
#       --db-url=pgsql://{{ pgsql_db_username }}:{{ pgsql_db_userpass }}@{{ pgsql_db_host}}:/{{ pgsql_db_name }}
#   args:
#     chdir: "/opt/www/sego.hu"
#   tags:
#     - drush
