- name: Download wp-cli command line interface for wordpress
  get_url: url=https://github.com/wp-cli/wp-cli/releases/download/v{{ wpcli_version }}/wp-cli-{{ wpcli_version }}.phar dest={{ wpcli_installdir }}/wp mode=0755

- name: Install wordpress with wp-cli
  command: wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} core download --locale={{ wpcli_core_locale }} creates={{ vhostspath }}/{{ vhostfqdn }}/index.php

- name: Configure wordpress database settings
  command: >
    wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} core config
    --dbname={{ mysql_db_name }}
    --dbuser={{ mysql_db_username }}
    --dbpass={{ mysql_db_userpass }}
    --dbhost={{ mysql_db_host }}
    creates={{ vhostspath }}/{{ vhostfqdn }}/wp-config.php
  register: wp_config

- name: Configure wordpress installation
  command: >
    wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} core install
    --url={{ vhostfqdn }}
    --title="{{ wpcli_core_title }}"
    --admin_user={{ wpcli_admin_user }}
    --admin_password={{ wpcli_admin_password }}
    --admin_email={{ wpcli_admin_email }}
  when: wp_config.changed

- name: Install wp-mail-smtp plugin
  command: wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} plugin install wp-mail-smtp --activate creates={{ vhostspath }}/{{ vhostfqdn }}/wp-content/plugins/wp-mail-smtp

- name: Install wordpress woocommerce
  command: wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} plugin install woocommerce --activate creates={{ vhostspath }}/{{ vhostfqdn }}/wp-content/plugins/woocommerce

- name: Install woocommerce storefront theme
  command: wp --allow-root --path={{ vhostspath }}/{{ vhostfqdn }} theme install storefront --activate creates={{ vhostspath }}/{{ vhostfqdn }}/wp-content/themes/storefront
